### ISSUE TITLE
Adding CSS/color theme 

### ISSUE THREAD

**Issue by jerler1** [ncastaldi/project1#49]
USER STORY: As a user, I want to access a website that looks well formatted and isn't hard to look at.

ACCEPTANCE CRITERIA
GIVEN I want to see a semi polished well formatted website
WHEN I access the website
THEN I expect to see containers well positioned, pictures position in a functional way that isn't glaring, and a color theme that flows well with other colors and doesn't blind the eye.

**Comment by ncastaldi** [comment]
Can we please do something about all the red? It's hard to look at. Maybe mostly neutral? And have colorful buttons?

**Comment by ncastaldi** [comment]
@mt428376 - Could you please apply a lighter color scheme?

**Comment by mt428376** [comment]
@ncastaldi Since the picky logo is black,white and red could I do the color scheme instead

**Comment by ncastaldi** [comment]
Sounds great! Mostly white/black with the buttons or tab headers set to red? Go ahead and create a branch and update the CSS, ok?
